### ISSUE TITLE
Fix app Architecture Collection?

### ISSUE THREAD

**Issue by apizz** [munkireport/applications#13] opened 2021-02-27 02:09 UTC
After ensuring my test munkireport instance was on the latest module version - 2.4 - it appears that despite while an architecture column exists it does not actually populate any information for the collected apps.

Appears #9 would address this.

**Comment by tuxudo** [comment] 2021-02-27 03:33
This should be addressed with PR #12. PR #9 appears to be an odd duplicate of PR #8

**Comment by tuxudo** [comment] 2021-02-27 13:50
Should be resolved with PR #14 and module version v2.5

**Comment by apizz** [comment] 2021-02-28 01:44
Can confirm

**Closed as completed** 2021-02-28 01:45 UTC
